import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import "@/src/styles/reset.css";
import "@/src/styles/normalize.css";
import "@/src/styles/globals.css";

import { Providers } from "../shared/redux/providers";

const montserrat = Montserrat({
	weight: ["500", "600", "700", "900"],
	style: ["normal", "italic"],
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "BookShop",
	description: "Generated by create next app",
};

import { Header } from "../widgets/ui/header";

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<Providers>
			<html lang="en">
				<body className={montserrat.className}>
					<Header />
					<div className="inner-container">{children}</div>
				</body>
			</html>
		</Providers>
	);
}
