import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Montserrat, Open_Sans } from "next/font/google";

import "@/src/styles/reset.css";
import "@/src/styles/normalize.css";
import "@/src/styles/globals.css";

import { Providers } from "../shared/redux/providers";

const montserrat = Montserrat({
	weight: ["500", "600", "700", "900"],
	style: ["normal", "italic"],
	subsets: ["latin"],
	variable: "--font-mont",
});

const opensans = Open_Sans({
	weight: ["400"],
	style: ["normal"],
	subsets: ["latin"],
	variable: "--font-open",
});

export const metadata: Metadata = {
	title: "BookShop",
	description: "Generated by create next app",
};

import { Header } from "../widgets/ui/header";

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<Providers>
			<html lang="en">
				<body className={`${montserrat.variable} ${opensans.variable}`}>
					<Header />
					<div className="inner-container">{children}</div>
				</body>
			</html>
		</Providers>
	);
}
